# Etiquetado de Componentes Conexos

In [1]:
import cv2
import numpy as np

In [36]:
imagen = cv2.imread("img/etiquetado.png", cv2.IMREAD_GRAYSCALE)
_, imagen_bin = cv2.threshold(imagen, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
cv2.imshow("Bin", imagen_bin)
cv2.waitKey(0)

-1

In [34]:
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(imagen_bin, 8, ltype=cv2.CV_32S)
print(f"Etiquetas_n: {num_labels} Etiquetas: {labels} Estadísticos: {stats} Centroides: {centroids}")

Etiquetas_n: 20 Etiquetas: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] Estadísticos: [[    0     0   330   248 67812]
 [  227     4    71   174  5554]
 [  235    22     1     1     1]
 [  193    83     4     3     5]
 [   34    84   191   138  8433]
 [  209    84     1     1     1]
 [  104   135     1     1     1]
 [  232   138     5     4     7]
 [   92   143     1     1     1]
 [   96   144     1     1     1]
 [   84   148     3     1     3]
 [   70   153     1     1     1]
 [   72   152     5     1     5]
 [   68   156     1     1     1]
 [   30   159     2     2     2]
 [   67   160     3     2     4]
 [   34   166     1     2     2]
 [   36   173     1     1     1]
 [   35   175     1     1     1]
 [   48   186     2     3     4]] Centroides: [[162.1066183  120.95407892]
 [254.47263234 106.16186532]
 [235.          22.        ]
 [194.4         84.        ]
 [124.72323017 155.30060477]
 [209.          84.  

In [35]:
for i in range(1, num_labels):
    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[i]
    if area > 100:
        cv2.rectangle(imagen, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(imagen, (int(cX), int(cY)), 4, (0, 0, 255), -1)
cv2.imshow('ImagenEtiquetada', imagen)
cv2.waitKey(0)
cv2.destroyAllWindows()