# Etiquetado de Componentes Conexos

In [1]:
import cv2
import numpy as np

In [ ]:
imagen = cv2.imread("img/etiquetado.jpg", cv2.IMREAD_GRAYSCALE)
_, imagen_bin = cv2.threshold(imagen, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
cv2.imshow("Bin", imagen_bin)
cv2.waitKey(0)

-1

In [29]:
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(imagen_bin, 8, ltype=cv2.CV_32S)
print(f"Etiquetas_n: {num_labels} Etiquetas: {labels} Estadísticos: {stats} Centroides: {centroids}")

Etiquetas_n: 1517 Etiquetas: [[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] Estadísticos: [[     0      0    784    485 298260]
 [     0      0      7      5     22]
 [     0      0     47     33    597]
 ...
 [   575    484      2      1      2]
 [   594    484      1      1      1]
 [   607    484      1      1      1]] Centroides: [[419.57320123 240.43485885]
 [  2.09090909   1.40909091]
 [ 17.52428811  12.33333333]
 ...
 [575.5        484.        ]
 [594.         484.        ]
 [607.         484.        ]]


In [30]:
for i in range(1, num_labels):
    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[i]
    if area > 100:
        cv2.rectangle(imagen, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(imagen, (int(cX), int(cY)), 4, (0, 0, 255), -1)
cv2.imshow('ImagenEtiquetada', imagen)
cv2.waitKey(0)
cv2.destroyAllWindows()