# Detección de Características en Imágenes

In [14]:
import cv2
import numpy as np
from skimage.feature import peak_local_max

In [ ]:
img = cv2.imread('img/cuadro.jpg', cv2.IMREAD_GRAYSCALE)
img = np.float32(img)

harris_corners = cv2.cornerHarris(img,2,3,0.04)
dst = cv2.dilate(harris_corners, None)

maxim = peak_local_max(dst, min_distance=1)
for coord in maxim:
    img[coord[0], coord[1]] = 255

In [16]:
maxim

array([[204, 214],
       [204, 215],
       [204, 216],
       ...,
       [354, 352],
       [354, 353],
       [354, 354]], shape=(121868, 2))

In [6]:
harris_corners

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(356, 356), dtype=float32)

In [7]:
img

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], shape=(356, 356), dtype=uint8)

In [9]:
cv2.imshow("Zamora", dst)
cv2.waitKey(0)

-1